### ISSUE TITLE
[Question] Splashscreen

### ISSUE THREAD

**Issue by Abesoddy** [hnabbasi/Themer#2]
Hello, 

Thanks for this great tutorial and Git repository. 

I had a quick question regarding the splashscreen. Is it possible to change the background color of the splashscreen depending on the theme?

**Comment by hnabbasi** [comment]
Absolutely. Check this blog post out by my buddy Brandon,


https://codetraveler.io/2019/10/11/creating-a-dark-mode-splash-screen/

**Comment by hnabbasi** [comment]
I hope that blog post answered your question. Closing this for now.
